harden-ssh-k8s-api-ports
seqeralabs/terraform-seqera-aws pull request #25
Opened 2023-11-24 13:53 UTC by enekui

## Description 
Added a set of new variables that will default to true to control SSH and Kubernetes API access to the EC2 instance.
Added a new Data source to conditionally get the public IP of the Terraform module operator. We are manipulating the output to get the clean public IP and pass it as the default allowed CIDR block to the SSH and Kubernetes API port. Also, there are two new variables to control this just in case it's needed to open SSH or Kubernetes API ports independently to everyone or other IPs/CIDR blocks. Removed unrelated left variables from ALB.
Updated README.md
Tested the new changes.

Note: *This is a small upgrade, but will make a huge difference in how customers take this from a security best practices point of view.*

2023-11-27 11:15 UTC, bebosudo approved these changes

2023-11-27 11:15 UTC, bebosudo commented on main.tf
> +  url   = "http://ipv4.icanhazip.com"
```suggestion
  url   = "https://ipv4.icanhazip.com"
```

2023-11-27 11:15 UTC, bebosudo commented on variables.tf
> +
```suggestion
```

2023-11-27 11:15 UTC, bebosudo commented on variables.tf
> +
```suggestion
```

2023-12-04 11:43 UTC, bebosudo approved these changes

2023-12-04 18:56 UTC, pditommaso requested changes

2023-12-04 18:56 UTC, pditommaso commented on examples/complete_public_ec2/main.tf
> +module "terraform-seqera-module" {
```suggestion
module "terraform-seqera-aws" {
```

2023-12-04 18:56 UTC, pditommaso commented on examples/complete_public_ec2/main.tf
> +  source = "/Users/adianny/seqera/git/terraform-seqera-module"
This looks a left over of the development

2023-12-08 00:00 UTC, ashseqera requested changes
@enekui  Noticed while adding EFS storage for the new ` monitoring `cluster that you have to add the `encrypted = true ` option while creating the EFS `resource "aws_efs_file_system" "eks_efs" ` otherwise the EFS data will be unencrypted

2023-12-13 10:13 UTC, bebosudo reviewed
Still some references to tower, there's a configmap called `kubernetes_config_map_v1.tower_app_configmap`

2023-12-13 10:52 UTC, bebosudo commented
I'm not discussing the use of a configmap, but its name. Do we want to rename it to Seqera platform or something?

2023-12-13 10:59 UTC, pditommaso commented
It's OK for now. There's a huge number of variable and settings prefixed with "tower". the idea is to keep this as near as possible to the current deployment

2023-12-13 11:32 UTC, bebosudo approved these changes
LGTM!

2023-12-13 11:41 UTC, ashseqera approved these changes
LGTM

2023-12-13 13:58 UTC, pditommaso commented
Sure, can you please make me a summary of the new settings introduced by this PR and the default value?

2023-12-18 11:52 UTC, pditommaso commented
Ok, thanks

2023-12-18 11:53 UTC, merged